metadata:
  submitted_by: kanwarpal.singh@cars24.com
  submitted_at: '2025-06-02T10:55:46.953471'
  user_name: Kanwarpal Singh
  business_unit: mkt_bi
configuration:
  database: cspl_mkt_db
  table: test_table
  schedule: 0 9 * * *
query: "-- Test Query \r\nselect current_timestamp as time;"
description: This is a test!
